DM-1089 :Creating a new deal with ABA format to verify that template type field is displaying
Frantz-B/cypress-automation-eval pull request #16
Opened 2020-02-11 13:31 UTC by Mkawad

- Creating a new Bidder via API
- Creating a new Deal-group via API
- Creating a new deal with ABA format via UI
- Verify that template type field is displaying via UI

2020-02-12 00:26 UTC, Frantz-B requested changes
I also recommend one way of achieving the ABA format test, is to first create the Deal with a different format, like how you did with your ticket DM-1090 (selecting bottom banner).  Then after that, when you go to edit the deal, you then select the ABA format.

2020-02-12 00:26 UTC, Frantz-B commented on cypress/integration/deal_template_type.js
> +/* eslint-disable linebreak-style */
Do not disable the line-break style

2020-02-12 00:26 UTC, Frantz-B commented on cypress/integration/deal_template_type.js
> +    });
If main focus is to Verify ABA format, then creating bidders should be done via API for speed.  There is already a UI test case that creates Bidders

2020-02-12 00:26 UTC, Frantz-B commented on cypress/integration/deal_template_type.js
> +    });
If main focus is to Verify ABA format, then there is no need to Edit and Validate a Bidder

2020-02-12 00:26 UTC, Frantz-B commented on cypress/integration/deal_template_type.js
> +
Only space is necessary

2020-02-12 00:26 UTC, Frantz-B commented on cypress/integration/deal_template_type.js
> +      });
If main focus is to Verify ABA format, then creating Deal-Group should be done via API for speed.  There is already a UI test case that creates Deal-Group

2020-02-12 00:26 UTC, Frantz-B commented on cypress/integration/deal_template_type.js
> +        });
This has to be updated to reflect new UI changes from DM-905

2020-02-12 00:26 UTC, Frantz-B commented on cypress/integration/deal_template_type.js
> +        cy.url().should('include', 'deal-dashboard/deals/edit/');
Pls add a validation/assertion section to cross check all the values that were entered to create the deal

2020-02-12 00:26 UTC, Frantz-B commented on cypress/integration/deal_template_type.js
> +    });
There should be a validation/assertion section that cross checks all the new values that were updated

2020-03-04 22:14 UTC, Frantz-B requested changes
I doubt the bidder-to-adServer.json file is need but explain to me why it is.  Other than that and changes I requested, add PR to DM automation repo

2020-03-04 22:14 UTC, Frantz-B commented on cypress/integration/deal_template_type.js
> +      cy.fixture('Bidder-to-adServer.json').then((bidder) => {
why does bidder POST need a km_id?

2020-03-04 22:14 UTC, Frantz-B commented on cypress/integration/deal_template_type.js
> +    });
What is the purpose of this function?

2020-03-05 12:17 UTC, Mkawad commented on cypress/integration/deal_template_type.js
> +    });
This function is needed to add a template to the deal

2020-03-05 12:18 UTC, Mkawad commented on cypress/integration/deal_template_type.js
> +      cy.fixture('Bidder-to-adServer.json').then((bidder) => {
To push the bidder to ad-server due to the deal only being pushed with a synced bidder

2023-06-10 06:36 UTC, Frantz-B commented
Closing this PR. but we do need aba template

2023-06-10 06:36 UTC, closed without merging